name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone submodules
      run: git submodule update --init --recursive
    - name: Add CMake PPA to get a reasonably updated version of CMake
      run: |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
    - name: Update the local repositories
      run: sudo apt-get update
    - name: Update CMake
      run: |
        sudo apt-get install cmake
        which cmake
    - name: Install SDL dependencies
      run: sudo apt-get install libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
    - name: Build PR
      if: github.ref != 'master'
      run: |
        cd build
        /usr/bin/cmake ..
        make
    - name: Build master
      if: github.ref == 'master'
      run: |
        cd build
        /usr/bin/cmake --config Release ..
        make
    - name: C++ check
      run: |
        sudo apt-get install cppcheck
        cppcheck --force ./
    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: build/
